### ISSUE TITLE
AttributeError: module 'model._C' has no attribute 'ps_roi_pool_forward

### ISSUE THREAD

**Issue by RuisongZhou** [McDo/PSROIAlign-Multi-Batch-PyTorch#1]
Hello, when I run your code, I suffered this question 
```
Traceback (most recent call last):
  File "example.py", line 83, in <module>
    psroipool_pooled_feat = psroipool_example(feature, rois)
  File "/home/zrs/env/pytorch1.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "example.py", line 27, in forward
    pooled_feat = self.psroipool(feat, rois)
  File "/home/zrs/env/pytorch1.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zrs/PSROIAlign-Multi-Batch-PyTorch/model/roi_layers/ps_roi_pool.py", line 77, in forward
    self.output_dim)
  File "/home/zrs/PSROIAlign-Multi-Batch-PyTorch/model/roi_layers/ps_roi_pool.py", line 20, in forward
    _C.ps_roi_pool_forward(ctx.pooled_height,
AttributeError: module 'model._C' has no attribute 'ps_roi_pool_forward'
```

My environment is :
pytorch 1.0
cuda 10.0

how can I solve it?

**Comment by McDo** [comment]
hi @RuisongZhou , did you build the _C module from scratch? any error logging?

**Comment by RuisongZhou** [comment]
I have soloved my problom by creating a new virtual environment. Maybe there are something wrong in my old environment.
Thanks!
